name: Build

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-20.04

    env:
      PLUGIN_NAME: ghcr.io/rtm516/docker-net-dhcp

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Install script dependencies
        run: pip3 install -r scripts/requirements.txt
        
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        
      - run: mkdir plugin

      - name: Build
        run: docker buildx build --platform=linux/arm/v7 -o type=local,dest=plugin/rootfs/ --tag ghcr.io/rtm516/docker-net-dhcp:release-linux-arm-v7 .
        
      - name: Plugin
        run: |
          cp config.json plugin/
          ls -la plugin/
          docker plugin create ghcr.io/rtm516/docker-net-dhcp:release-linux-arm-v7 plugin
          docker plugin push ghcr.io/rtm516/docker-net-dhcp:release-linux-arm-v7
